name: TIL (Today I Learned)
description: 오늘 새롭게 배운 내용을 정리해보세요.
labels: [TIL, learning]

body:
  - type: textarea
    id: what-you-learned
    attributes:
      label: 📌 배운 내용
      description: 오늘 새롭게 배운 내용을 구체적으로 작성해주세요. 기존에 알고 있던 내용과의 차이점이나 오해했던 부분이 있다면 함께 작성하면 좋아요.
      placeholder: |
        예) useEffect cleanup 함수의 정확한 동작 방식에 대해 알게 되었어요.
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 🔍 배경 / 문제 상황
      description: 어떤 상황에서 이 내용을 알게 되었는지 작성해주세요. 실제 작업 중 발생한 이슈 번호나 트러블슈팅 중 배운 점이면 이슈 번호도 함께 적어주세요.
      placeholder: |
        예) #42 이슈에서 발생한 styled-components 관련 버그를 해결하는 과정에서 알게 되었어요.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: ✅ 핵심 정리 / 해결 방법
      description: 알게 된 개념을 짧고 명확하게 정리해주세요. 코드 예시, 이미지, 도식 등을 활용해도 좋아요.
      placeholder: |
        예)
        ```js
        // 조건부 스타일 적용
        css={[defaultStyle, isActive && activeStyle]}
        ```
    validations:
      required: true

  - type: textarea
    id: thought
    attributes:
      label: 🧠 느낀점 또는 생각 메모
      description: 배운 내용에 대한 느낀 점이나 의문이 생긴 부분을 자유롭게 작성해주세요.
      placeholder: |
        예) 이 내용은 좀 더 테스트해봐야 할 것 같아요. 혹시 더 좋은 접근이 있을까요?
    validations:
      required: false

  - type: textarea
    id: reference
    attributes:
      label: 📚 래퍼런스
      description: 참고한 링크나 문서를 적어주세요. 없으면 생략해도 좋아요.
      placeholder: |
        예) https://beta.reactjs.org/learn/synchronizing-with-effects
    validations:
      required: false
