import './globals.css'

import type { Metadata } from 'next'

import { Providers } from './providers'
import ThemeToggle from './shared/components/ThemeToggle'

export const metadata: Metadata = {
  title: 'Coplan',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeToggle />
          {/* 푸쉬하기 전에 이거 삭제해야함 */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
