import './globals.css'

import type { Metadata } from 'next'
import { Toaster } from 'sonner'

import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Coplan',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          {children}
          <Toaster position="top-right" richColors closeButton />
        </Providers>
        <div id="modal-root" />
      </body>
    </html>
  )
}
